import { ApiResponse, OnboardingType, QnaType } from '@/api/api.types';
import { GrowthXForms } from '@/components/views';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import fs from 'node:fs/promises';
import path from 'path';
import React from 'react';

const Home: React.FC<InferGetServerSidePropsType<typeof getServerSideProps>> = (
  props
) => {
  return (
    <React.Fragment>
      <Head>
        <title>GrowthX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GrowthXForms data={props.data} />
    </React.Fragment>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<
  ApiResponse<OnboardingType, QnaType>
> = async () => {
  const dir = path.resolve(process.cwd(), 'db', 'data.json');
  const data = JSON.parse(await fs.readFile(dir, 'utf-8'));
  return {
    props: { data },
  };
};
