name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print secrets
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker-compose -f docker-compose.yml build
          docker tag growthx-app ${{ secrets.DOCKER_HUB_USERNAME }}/growthx-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/growthx-app:${{ github.sha }}

      # - name: Deploy to Cloudflare Pages
      #   uses: cloudflare/pages-deploy@v3
      #   with:
      #     CF_PAGES_API_TOKEN: ${{ secrets.CF_PAGES_API_TOKEN }}
      #     CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      #     CF_PAGES_SPACE_ID: ${{ secrets.CF_PAGES_SPACE_ID }}
      #     CF_PAGES_SITE_ID: ${{ secrets.CF_PAGES_SITE_ID }}
      #     BUILD_COMMAND: 'docker-compose -f docker-compose.yml up'
      #     BUILD_DIR: '.'
      #     DEPLOYMENT_URL: '<your production deployment URL>'
